Import('*')

if env['TARGET_ISA'] != 'no':
    Source('gpu_syscall_helper.cc')
    Source('gpu_syscalls.cc', Werror=False)
    Source('cuda_syscalls.cc', Werror=False)
    Source('ocl_syscalls.cc', Werror=False)

DebugFlag('GPUSyscalls')
